name:                waterdata-usgs
version:             0.1.0.0
github:              "jfennick/waterdata-usgs"
license:             BSD3
author:              "Jake Fennick"
maintainer:          "jfennick@github.com"
copyright:           "2018 Jake Fennick"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/jfennick/waterdata-usgs#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

executables:
  waterdata-usgs-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - waterdata-usgs
    - aeson
    - connection
    - bytestring
    - gnuplot
    - http-conduit
    - http-types
    - unordered-containers
    - text
    - time
    - vector
    - zlib

tests:
  waterdata-usgs-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - waterdata-usgs
